default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: vpsproject_development

test:
  <<: *default
  database: vpsproject_test

production:
  <<: *default
  adapter: mysql2
  database: vpsproject_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /run/mysqld/mysqld.sock
