default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: vpsproject_development

test:
  <<: *default
  database: vpsproject_test

production:
  <<: *default
  database: vpsproject_production
  username: deploy
  # password: <%= ENV['DATABASE_PASSWORD'] %>
  password: nLpp375Fr@&Z
